### ISSUE TITLE
changes

### ISSUE THREAD

**Issue by collinsetta63** [vivek-mishra04/test#1]
am using a different host. 
please what do i need to change in the "onlineshop.sql" file
![com](https://user-images.githubusercontent.com/44732692/78714281-83280900-7913-11ea-8f34-9ce62555714c.png)

**Comment by vivek-gaia** [comment]
I think a passing the hostname similar to this should work:
`CREATE DEFINER='username'@'192.168.0.5' PROCEDURE ...` where `username` is the db username and `192.168.0.5` is the host ip address

**Comment by collinsetta63** [comment]
is still giving me the same error
